name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Check for linting issues
        run: pnpm lint
      - name: Run functional tests
        run: pnpm test:func:run
